ansible_become: true
kubeadm_enabled: true
kube_api_anonymous_auth: true
kube_kubeadm_apiserver_extra_args:
  service-account-issuer: "kubernetes.default.svc"
  service-account-signing-key-file: "/etc/kubernetes/ssl/sa.key"
# Set to false due to kubespray bug: https://github.com/kubernetes-sigs/kubespray/issues/5059
kubectl_localhost: false
kubeconfig_localhost: true
helm_enabled: true
tiller_node_selectors: "node-role.kubernetes.io/master=''"

## Container runtime
## docker for docker, crio for cri-o and containerd for containerd.
container_manager: containerd

artifacts_dir: "{{ inventory_dir }}/artifacts"

# Reset Flex Volume path to the default. Kubespray changes the path, which breaks Rook
# see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-storage/flexvolume.md
kubelet_flexvolumes_plugins_dir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec

# Provide option to use GPU Operator instead of setting up NVIDIA driver and
# Docker configuration.
deepops_gpu_operator_enabled: false

# Install NVIDIA Driver and nvidia-docker on node (true), not as part of GPU Operator (driver container, nvidia-toolkit) (false)
gpu_operator_preinstalled_nvidia_software: true

# Set the MIG labeling and use strategy to none, single, or mixed. See https://github.com/NVIDIA/k8s-device-plugin
k8s_gpu_mig_strategy: "mixed"

# When set to true, enables the PodSecurityPolicy admission controller and
# defines two policies: privileged (applying to all resources in kube-system
# namespace and kubelet) and restricted (applying all other namespaces).
# Addons deployed in kube-system namespaces are handled.
#podsecuritypolicy_enabled: false

# Pin the version of kubespray dashboard https://github.com/kubernetes/dashboard/releases/tag/v2.0.3
dashboard_enabled: true
dashboard_image_tag: "v2.0.3"
dashboard_image_repo: "kubernetesui/dashboard"
dashboard_metrics_scrape_tagr: "v1.0.4"
dashboard_metrics_scraper_repo: "kubernetesui/metrics-scraper"

# Ensure hosts file generation only runs across k8s cluster
hosts_add_ansible_managed_hosts_groups: ["k8s-cluster"]

# NFS Client Provisioner 
# Playbook: nfs-client-provisioner.yml
#k8s_nfs_client_provisioner: true
#k8s_deploy_nfs_server: true
#k8s_nfs_mkdir: true # Set to false if an export dir is already configured with proper permissions
#k8s_nfs_server: '{{ groups["kube-master"][0] }}'
#k8s_nfs_export_path: '/export/deepops_nfs'

# NFS Server
# This config will create an NFS server and share the given exports
# Playbook: nfs-server.yml, nfs-provisioner-client.yml
#nfs_exports:
#  - path: '{{ k8s_nfs_export_path }}'
#    options: "*(rw,sync,no_root_squash)"

################################################################################
# SPACE Customization                                                          #
################################################################################
# Versions
#kube_version: v1.21.6
#containerd_version: 1.5.8
#cni_version: "v1.0.1"
#etcd_version: v3.5.0
#calico_version: "v3.20.3"
#multus_version: "v3.7.2"
#helm_version: "v3.7.1"
#gpu_operator_chart_version: v22.9.0

# Calico Config
calico_ipip_mode: Always  # valid values are 'Always', 'Never' and 'CrossSubnet'
calico_vxlan_mode: Never  # valid values are 'Always', 'Never' and 'CrossSubnet'
calico_network_backend: bird

# Addons
addon_dir: "{{ inventory_dir }}/../addon"
artifacts_yaml_dir: "{{ artifacts_dir }}/yaml"

node_labeling: true
deploy_harbor: false

# To remove --insecure flag in default value,
# so that it can download images with nerdctl
nerdctl_extra_flags: ""

# k8s cluster options
kube_apiserver_port: 6443
