# Specific Variables

# PROXY
# Proxy Variables needed for scripts, ansible, etc.
#http_proxy: http://IP:Port
#https_proxy: http://IP:Port
#no_proxy: localhost,*.cluster.local,127.0.0.1,::1,10.233.0.0/16,cloud

#proxy_env:
#  http_proxy: '{{ http_proxy }}'
#  https_proxy: '{{ https_proxy }}'
#  no_proxy: '{{ no_proxy }}'

# Container registry
containerd_registries:
  "docker.io":
    - "https://registry-1.docker.io"

#containerd_insecure_registries:
#  "192.168.1.193:8083":
#    - "http://192.168.1.193:8083"
#  "registry.ocp4.exp.com:5000":
#    - "https://registry.ocp4.exp.com:5000"

#containerd_registry_auth:
#  - registry: registry.ocp4.exp.com:5000
#    username: admin
#    password: admin

calico_pool_blocksize: 24
