apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-static-diag-infra
  #namespace: diag-infra
spec:
  storageClassName: storageclass-n6-sgcp-mgmt-system
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5G
