---

containerd_cfg_dir: "/etc/containerd"
containerd_storage_dir: "/var/lib/containerd"
containerd_state_dir: "/run/containerd"
containerd_systemd_dir: "/etc/systemd/system/containerd.service.d"
containerd_oom_score: 0

containerd_use_systemd_cgroup: true

containerd_default_runtime: "runc"
# containerd_snapshotter: "native"

containerd_runc_runtime:
  name: runc
  type: "io.containerd.runc.v2"
  engine: ""
  root: ""
  options:
    systemdCgroup: "{{ containerd_use_systemd_cgroup | ternary('true', 'false') }}"
    
containerd_additional_runtimes: []
# Example for Kata Containers as additional runtime:
#  - name: kata
#    type: "io.containerd.kata.v2"
#    engine: ""
#    root: ""

kata_containers_enabled: false
gvisor_enabled: false
    
containerd_grpc_max_recv_message_size: 16777216
containerd_grpc_max_send_message_size: 16777216

pod_infra_image_repo: "k8s.gcr.io/pause"
pod_infra_image_tag: "3.3"


containerd_registries:
  "docker.io": "https://registry-1.docker.io"

containerd_max_container_log_line_size: -1

# Extra config to be put in {{ containerd_cfg_dir }}/config.toml literally
containerd_extra_args: ''

# Configure registry auth (if applicable to secure/insecure registries)
containerd_registry_auth: []
#  - registry: 10.0.0.2:5000
#    username: user
#    password: pass
