---

- name: Diag Func | Copy Test python files on node
  copy:
    src: diag-infra.tar.gz
    dest: /tmp/diag-infra.tar.gz

- name: Diag Func | Extract Test python files on node
  unarchive:
    src: /tmp/diag-infra.tar.gz
    dest: /mnt/
    remote_src: yes
  become: yes

- name: Diag Func | Testing network function on host
  shell: python3 /mnt/diag-infra/func_host_teleport.py --params={{ cluster }} --diag_id=1 --log=file
  register: network_host_test
  tags: func_host_teleport 

- debug:
    msg: "{{ network_host_test }}"
