---
- name: Diag Func | Copy to node for deploy yaml
  template:
    src: gdr_pod.yaml.j2
    dest: /tmp/gdr-pod-{{ item }}.yaml
  become: yes
  with_items:
    - "{{ ansible_hostname }}"
  vars:
    num: 1

- name: Diag Func | Deploy test gdr pod on kubernetes
  shell: kubectl apply -f  /tmp/gdr-pod-{{ item }}.yaml
  become: yes
  with_items:
    - "{{ ansible_hostname }}"
    
